//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unity.VisualScripting.Generated.PropertyProviders
{
	
	
	[global::Unity.VisualScripting.SerializedPropertyProviderAttribute(typeof(global::Unity.Tutorials.Core.Editor.GoingBackEvent))]
	public class PropertyProvider_Unity_Tutorials_Core_Editor_GoingBackEvent : Unity.VisualScripting.SerializedPropertyProvider<Unity.Tutorials.Core.Editor.GoingBackEvent>
	{
	}
}
